GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDk1ZWY3ZTlmNjNiZTg3M2VmYzFlMWUiLCJlbWFpbCI6Imhlcm1pb25lQGdtYWlsLmNvbSIsImlhdCI6MTY4NzcyOTI5MCwiZXhwIjoxNjg3NzI5MzUwfQ.pUxHblMbP9lC-k50frY73IHjd_U4B6SYHDtjdEA_InU HTTP/1.1