POST http://localhost:5000/api/users/sign-in HTTP/1.1
Content-Type: application/json

{
    "firstName": "My",
    "lastName": "Mine",
    "email": "minemine@gmail.com",
    "birthday": "1989-10-10",
    "password": "mine"
}